extract_curriculum_data:
  description: >
    Leia o arquivo de currículo fornecido via 'src/inputs'.
    Determine se é um arquivo PDF ou LaTeX e use a ferramenta apropriada (PDFSearchTool para PDF, LatexReaderTool para LaTeX).
    Extraia uma lista estruturada contendo:
    - Experiências profissionais
    - Habilidades
    - Formação acadêmica
    Após a extração, gere um relatório detalhado e salve-o como 'extract_curriculum_data_report.md'.
    Além da estrutura dos dados, inclua informações adicionais relevantes, pois as informaçoes destes curriculos devem ser utilizadas para criar o novo curriculo. 
  expected_output: >
    Um dicionário estruturado com os dados extraídos do currículo (experiências, habilidades, educação).
    O contexto deve ser nomeado 'extract_curriculum_data' para a próxima tarefa.
    os dados do candidato devem ser extraídos e organizados em um formato estruturado, como JSON ou YAML.
    O arquivo deve conter informaçoes detalhadas para que sejam aperfeiçoadas nas etapas seguintes.
    Um arquivo data_curriculum.md
    Um arquivo extract_curriculum_data_report.md
  agent: curriculum_reader
  inputs:
    resume_path:: str(input_dir / 'curriculum.tex'),
    file_path': str(input_dir / 'curriculum.pdf'),
    query: "Extract professional experiences and academic background. For skills, search headings like 'Competências Técnicas', 'Competências Linguísticas' or 'Skills', and extract the items listed under these sections."
  output_file: extract_curriculum_data_report.md

explain_curriculum_learning:
  description: >
    Com base no conteúdo extraído pelo PDFSearchTool e LatexReaderTool na tarefa 'extract_curriculum_data', explique o que foi aprendido usando cada ferramenta.
    Após a explicação, gere um relatório detalhado e salve-o como 'explain_curriculum_learning_report.md'.
  expected_output: >
    Um arquivo markdown com seções para PDFSearchTool e LatexReaderTool resumindo os insights extraídos.
    Um arquivo explain_curriculum_learning_report.md
  agent: curriculum_reader
  context:
    - extract_curriculum_data_task
  output_file: 
   explain_curriculum_learning_report.md

analyze_job_description:
  description: >
    Analise a descrição do trabalho fornecida.
    Se um URL for fornecido ({job_url}), extraia o conteúdo do URL.
    Se texto for fornecido diretamente ({job_text}), utilize este texto.
    Extraia os requisitos técnicos principais, experiências valorizadas e palavras-chave relevantes.
    Após a análise, gere um relatório detalhado e salve-o como 'analyze_job_description_report.md'.
  expected_output: >
    Um resumo em tópicos destacando os requisitos principais e aspectos a enfatizar no currículo, com base na análise da descrição do trabalho.
    Um arquivo analyze_job_description_report.md
  agent: job_analyzer
  output_file: 
    analyze_job_description_report.md

# Novas Tarefas para Análise Semântica
embed_curriculum:
  description: >
    Recebe o texto estruturado do currículo extraído pela tarefa 'extract_curriculum_data'.
    Utiliza a 'Text Embedding Tool' para gerar um vetor semântico (embedding) para o conteúdo do currículo.
  expected_output: >
    Uma lista de floats representando o embedding do currículo.
    Este output será usado como contexto para a tarefa 'analyze_similarity'.
  agent: alignment_analyzer
  context:
    - extract_curriculum_data_task

embed_job_description:
  description: >
    Recebe o texto da descrição da vaga analisado pela tarefa 'analyze_job_description'.
    Utiliza a 'Text Embedding Tool' para gerar um vetor semântico (embedding) para o conteúdo da descrição da vaga.
  expected_output: >
    Uma lista de floats representando o embedding da descrição da vaga.
    Este output será usado como contexto para a tarefa 'analyze_similarity'.
  agent: alignment_analyzer
  context:
    - analyze_job_description_task

analyze_similarity:
  description: >
    Recebe os embeddings do currículo (da tarefa 'embed_curriculum') e da descrição da vaga (da tarefa 'embed_job_description').
    Utiliza a 'Semantic Similarity Tool' para calcular a similaridade de cosseno entre os dois embeddings.
    Gera um relatório conciso indicando o score de similaridade e uma breve interpretação (ex: 'Alto Alinhamento', 'Alinhamento Moderado', 'Baixo Alinhamento').
    Identifica e lista os principais pontos fortes (onde a semelhança é alta) e os principais pontos a desenvolver/estudar (onde a semelhança é baixa), baseando-se na análise semântica.
  expected_output: >
    Um relatório em markdown ('similarity_analysis_report.md') contendo:
    - O score de similaridade.
    - Uma interpretação do score.
    - Lista de pontos fortes.
    - Lista de pontos a desenvolver/estudar.
    Este relatório será usado como contexto para a tarefa 'adjust_resume_for_job' e 'generate_report'.
  agent: alignment_analyzer
  context:
    - embed_curriculum_task
    - embed_job_description_task
  output_file: similarity_analysis_report.md

adjust_resume_for_job:
  description: >
    Usando os dados estruturados do currículo da tarefa 'extract_curriculum_data', o resumo da análise do trabalho da tarefa 'analyze_job_description', E o relatório de similaridade da tarefa 'analyze_similarity' como contexto, reescreva e reorganize seções do conteúdo original do currículo para melhorar o alinhamento com o trabalho alvo.
    Concentre-se em destacar habilidades e experiências relevantes com base *apenas* no conteúdo do currículo fornecido. Não invente novas informações ou experiências.
    Após o ajuste, gere um relatório detalhado e salve-o como 'adjust_resume_for_job_report.md'.
    Siga estas diretrizes:
    - Enfatize conteúdo relevante para o trabalho para melhorar a pontuação ATS. Evite gráficos complexos, a menos que solicitado.
    - Priorize habilidades e qualificações sobre dados pessoais.
    - Organize as informações estrategicamente para facilitar a leitura.
    - Defina o campo Objetivo para: "Atuar como [cargo]" (onde [cargo] é inferido da descrição do trabalho).
    - Certifique-se de que o conteúdo final do currículo seja conciso, idealmente cabendo em duas páginas quando compilado.
  expected_output: >
    O conteúdo completo e modificado do currículo como um único bloco de código LaTeX, salvo em um arquivo `.tex`.
    Um arquivo adjust_resume_for_job_report.md
  agent: resume_editor
  context: # Adicionado analyze_similarity ao contexto
    - extract_curriculum_data_task
    - analyze_job_description_task
    - analyze_similarity_task
  output_file: 
     novo_curriculo.tex
     adjust_resume_for_job_report.md

generate_report:
  description: >
    Compile um relatório detalhado documentando a execução de cada tarefa anterior (
      'extract_curriculum_data', 
      'analyze_job_description', 
      'embed_curriculum', 
      'embed_job_description', 
      'analyze_similarity', 
      'adjust_resume_for_job'
    ).
    Para cada tarefa, inclua:
    - O agente responsável.
    - O objetivo da tarefa.
    - Um resumo dos resultados ou saídas geradas.
    - Quaisquer observações ou desafios encontrados durante a execução (se disponíveis no contexto).
    Após a compilação, gere um relatório detalhado e salve-o como 'generate_report_report.md'.
  expected_output: >
    Um arquivo markdown (`execution_report.md`) contendo o relatório estruturado da execução da equipe.
    Um arquivo generate_report_report.md
  agent: reporting_agent
  output_file: 
   execution_report.md
   generate_report_report.md
